// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/email.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_proto_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{0}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailResponse) Reset() {
	*x = EmailResponse{}
	mi := &file_proto_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailResponse) ProtoMessage() {}

func (x *EmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailResponse.ProtoReflect.Descriptor instead.
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{1}
}

func (x *EmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{2}
}

type EmailListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailListResponse) Reset() {
	*x = EmailListResponse{}
	mi := &file_proto_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailListResponse) ProtoMessage() {}

func (x *EmailListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailListResponse.ProtoReflect.Descriptor instead.
func (*EmailListResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_proto_rawDescGZIP(), []int{3}
}

func (x *EmailListResponse) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

var File_proto_email_proto protoreflect.FileDescriptor

const file_proto_email_proto_rawDesc = "" +
	"\n" +
	"\x11proto/email.proto\x12\x05email\"$\n" +
	"\fEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"C\n" +
	"\rEmailResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\a\n" +
	"\x05Empty\"+\n" +
	"\x11EmailListResponse\x12\x16\n" +
	"\x06emails\x18\x01 \x03(\tR\x06emails2{\n" +
	"\fEmailService\x125\n" +
	"\bAddEmail\x12\x13.email.EmailRequest\x1a\x14.email.EmailResponse\x124\n" +
	"\n" +
	"ListEmails\x12\f.email.Empty\x1a\x18.email.EmailListResponseB\bZ\x06proto/b\x06proto3"

var (
	file_proto_email_proto_rawDescOnce sync.Once
	file_proto_email_proto_rawDescData []byte
)

func file_proto_email_proto_rawDescGZIP() []byte {
	file_proto_email_proto_rawDescOnce.Do(func() {
		file_proto_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_email_proto_rawDesc), len(file_proto_email_proto_rawDesc)))
	})
	return file_proto_email_proto_rawDescData
}

var file_proto_email_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_email_proto_goTypes = []any{
	(*EmailRequest)(nil),      // 0: email.EmailRequest
	(*EmailResponse)(nil),     // 1: email.EmailResponse
	(*Empty)(nil),             // 2: email.Empty
	(*EmailListResponse)(nil), // 3: email.EmailListResponse
}
var file_proto_email_proto_depIdxs = []int32{
	0, // 0: email.EmailService.AddEmail:input_type -> email.EmailRequest
	2, // 1: email.EmailService.ListEmails:input_type -> email.Empty
	1, // 2: email.EmailService.AddEmail:output_type -> email.EmailResponse
	3, // 3: email.EmailService.ListEmails:output_type -> email.EmailListResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_email_proto_init() }
func file_proto_email_proto_init() {
	if File_proto_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_email_proto_rawDesc), len(file_proto_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_email_proto_goTypes,
		DependencyIndexes: file_proto_email_proto_depIdxs,
		MessageInfos:      file_proto_email_proto_msgTypes,
	}.Build()
	File_proto_email_proto = out.File
	file_proto_email_proto_goTypes = nil
	file_proto_email_proto_depIdxs = nil
}
